stages:
  - test
  - build
  - deploy

variables:
  IMAGE: bunny324/practice

test:
  stage: test
  tags:
    - self-hosted
  script:
    - npm install
    - npm test

build_and_push:
  stage: build
  tags:
    - self-hosted
  script:
    - echo "$DOCKERHUB_TOKEN" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
    - docker build -t $IMAGE:$CI_COMMIT_SHORT_SHA .
    - trivy image --severity HIGH,CRITICAL --exit-code 0 $IMAGE:$CI_COMMIT_SHORT_SHA
    - docker push $IMAGE:$CI_COMMIT_SHORT_SHA

update_manifest:
  stage: deploy
  tags:
    - self-hosted
  script:
    - "sed -i '' \"s|image: $IMAGE:.*|image: $IMAGE:$CI_COMMIT_SHORT_SHA|\" k8s/deployment.yaml"
    - git config user.name "gitlab-ci"
    - git config user.email "gitlab-ci@example.com"
    - git remote set-url origin git@gitlab.com:nk780877/devops-pipeline-app.git
    - git commit -am "Update image to $CI_COMMIT_SHORT_SHA [skip ci]"
    - git fetch origin main
    - git rebase origin/main
    - git push origin HEAD:main
  only:
    - main
