apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: devops-pipeline-app
  namespace: argocd
spec:
  project: devops-pipeline-project
  source:
    repoURL: https://github.com/shahzaib-rehman005/devops-pipeline-app.git
    targetRevision: main
    path: helm/devops-pipeline-app
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
