apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: app-monitor
  namespace: {{ .Values.monitoring.namespace }}
  labels:
    release: monitoring
spec:
  selector:
    matchLabels:
      app: app
  namespaceSelector:
    matchNames:
      - default
  endpoints:
    - port: "{{ .Values.service.port }}"
      path: /metrics
